# Generated by Django 5.2.8 on 2025-11-22 14:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Localization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('localization', models.CharField(max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='Component',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=6)),
                ('quantity', models.PositiveIntegerField()),
                ('localization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Warehouse_System.localization')),
            ],
        ),
    ]
