# Generated by Django 5.2.8 on 2025-11-22 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Warehouse_System', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='localization',
            old_name='localization',
            new_name='localization_name',
        ),
    ]
