# Generated by Django 5.2.8 on 2025-11-24 20:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Warehouse_System', '0002_rename_localization_localization_localization_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='component',
            name='localization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='components', to='Warehouse_System.localization'),
        ),
    ]
